### PR TITLE
Show that user is signed in after logging in after voting.

### LINKED ISSUE #8: If you're logged out, then upvote, the login page appears but doesn't actually log you in.
- If you're logged out, then upvote, the login page appears but doesn't actually log you in.

### PR DESCRIPTION
**Pull request by patbl**
Fixes #8.

### CODE REVIEW

**Comment by OAGr** [comment]
Good job Patrick!

**Comment by patbl** [comment]
It would be nice to upvote/downvote after log-in as well, but we can do that in a separate pull request.

**Comment by tog22** [comment]
Looking at the comment in your commit code, how likely are there to end up being params? Would they be there if someone had arrived via a ?utm_source=xxx link .

Btw @peterhurford is setting the github development protocol and likes people just developing on  branches in tog22/eaforum.

**Comment by arichard4** [comment]
Proposal: 

``` python
if '?' in dest:
   res._redirect(dest + "&h=t")
else:
   res._redirect(dest + "?h=t")
```

**Comment by tog22** [comment]
Seems good, I've merged and I'll let Patrick add that to tog22:master with a further commit direct to there.

**Pull request merged**
