### PR TITLE
Allows mods/admins to delete posts

### PR DESCRIPTION
**Pull request by arichard4**
As per issue tog22/eaforum#4

There is now a link (saying delete) in the bottom right of the post, when the mod/admin is on the full-page version of the post (not the summary).

### CODE REVIEW

**Comment by peterhurford** [comment]
Live QA'd -- confirmed admins can delete posts and normal Joes cannot.

**Comment by RyanCarey** [comment]
Phew, we've been lucky not to have any severe troublemakers in the forum's initial months! Now we could reduce the karma threshold for posting a thread from 10 to 5 if you guys want to. Whatever you think is a good thing!

**Comment by tog22** [comment]
Sounds worth at least experimenting with - though if you like you/we could
probably get a broader community take in the .impact FB group or perhaps
better in a forum thread/open thread.

## 

I receive a lot of email and limit my time spent on it, so may take a while
to see or reply to messages; I may be able to reply more quickly to emails
with an indication of timeframes (e.g. with 'urgent' in the subject line).

Contact information: http://bit.ly/tagoogleplus

**Comment by RyanCarey** [comment]
If we're just trialling it, which we are, then it's too trivial a decision to need to consult.

Ryan Carey | bioinformatics student | medical resident

**Comment by peterhurford** [comment]
Agree. :+1:

**Comment by tog22** [comment]
Cool, is that something you can change Ryan or do we/people we've recruited
need to change the code?

## 

I receive a lot of email and limit my time spent on it, so may take a while
to see or reply to messages; I may be able to reply more quickly to emails
with an indication of timeframes (e.g. with 'urgent' in the subject line).

Contact information: http://bit.ly/tagoogleplus

**Comment by RyanCarey** [comment]
I don't think it's in any mod interface, would have to be changed in the
code.

Ryan Carey | bioinformatics student | medical resident

**Comment by tog22** [comment]
Cool, I've created an issue  - #21 - and assigned one of our team.

## 

I receive a lot of email and limit my time spent on it, so may take a while
to see or reply to messages; I may be able to reply more quickly to emails
with an indication of timeframes (e.g. with 'urgent' in the subject line).

Contact information: http://bit.ly/tagoogleplus

**Pull request merged**
